/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto;
import punto.panel; 
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author chiqu
 */
public class cliente extends javax.swing.JFrame {

    /**
     * Creates new form empleado
     */
    public cliente() {
        initComponents();
        cargarClientes();
        
        jButton1.addActionListener(evt -> agregarCliente());
}
    
  private void agregarCliente() {
        String nombre = jTextFilNombre.getText();
        String direccion = jTextFilDireccion.getText();
        String telefono = jTextFilTelefono.getText();
        String email = jTextField4.getText();

        if (nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor llena todos los campos.");
            return;
        }

        try (Connection con = getConnection()) {
            String sql = "INSERT INTO clientes (nombre, direccion, telefono, email) VALUES (?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, nombre);
            ps.setString(2, direccion);
            ps.setString(3, telefono);
            ps.setString(4, email);
            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Cliente agregado correctamente");
                limpiarCampos();
                cargarClientes();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar el cliente.");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al insertar: " + ex.getMessage());
        }
    }
  private Connection getConnection() throws SQLException {
    String url = "jdbc:mysql://localhost:3306/negocio"; // Cambia 'negocio' por tu base si es otro nombre
    String user = "root"; // Tu usuario de MySQL
    String password = "19971103"; // Tu contraseña de MySQL, si es que tienes

    return DriverManager.getConnection(url, user, password);
}


    private void cargarClientes() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Dirección", "Teléfono", "Email", "Registrado"});
        jTable1.setModel(modelo);

        try (Connection con = getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM clientes")) {

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id_cliente"),
                    rs.getString("nombre"),
                    rs.getString("direccion"),
                    rs.getString("telefono"),
                    rs.getString("email"),
                    rs.getString("fecha_registro")
                });
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + ex.getMessage());
        }
    }

    private void limpiarCampos() {
        jTextFilNombre.setText("");
        jTextFilDireccion.setText("");
        jTextFilTelefono.setText("");
        jTextField4.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JLabel();
        txtDirreccion = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        jTextFilNombre = new javax.swing.JTextField();
        jTextFilTelefono = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();
        jTextFilDireccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtNombre.setText("Nombre");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtDirreccion.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtDirreccion.setText("Dirreccion");
        getContentPane().add(txtDirreccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtTelefono.setText("Telefono");
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jTextFilNombre.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        getContentPane().add(jTextFilNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 270, -1));

        jTextFilTelefono.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        getContentPane().add(jTextFilTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 270, -1));

        jTextField4.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 270, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jButton1.setText("Agregar empleado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jButton2.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Quitar empleado");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 200, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 580, -1));

        Regresar.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        txtEmail.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtEmail.setText("E-mail");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jTextFilDireccion.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        getContentPane().add(jTextFilDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 270, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        agregarCliente();
    }
});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
      panel p = new panel(); // Cambia 'panel' por el nombre real de tu JFrame principal
    p.setVisible(true);
    this.dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     java.awt.EventQueue.invokeLater(() -> new cliente().setVisible(true));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFilDireccion;
    private javax.swing.JTextField jTextFilNombre;
    private javax.swing.JTextField jTextFilTelefono;
    private javax.swing.JLabel txtDirreccion;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
