

package punto;


public class inventario extends javax.swing.JFrame {

    /**
     * Creates new form inventario
     */
    public inventario() {
        initComponents();
         }
               
     private void agregarProducto() {
    try {
        String idTexto = txtid.getText().trim();
        String nombre = txtnombre.getText().trim();
        String cantidadTexto = txtcantidad.getText().trim();

        if (idTexto.isEmpty() || nombre.isEmpty() || cantidadTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
            return;
        }

        int id = Integer.parseInt(idTexto);
        int cantidad = Integer.parseInt(cantidadTexto);

        java.sql.Connection con = conex.Conexion.getConexion();

        // Verificar si el producto ya existe
        String verificarSQL = "SELECT COUNT(*) FROM productos WHERE id_producto = ?";
        java.sql.PreparedStatement verificarStmt = con.prepareStatement(verificarSQL);
        verificarStmt.setInt(1, id);
        java.sql.ResultSet rs = verificarStmt.executeQuery();
        rs.next();
        boolean existe = rs.getInt(1) > 0;

        if (existe) {
            javax.swing.JOptionPane.showMessageDialog(this, "El producto ya existe. Usa editar para modificarlo.");
            return;
        }

        // Insertar en productos
        String sqlInsertar = "INSERT INTO productos (id_producto, nombre, stock, categoria_id, precio_unitario) VALUES (?, ?, ?, ?, ?)";
        java.sql.PreparedStatement ps = con.prepareStatement(sqlInsertar);
        ps.setInt(1, id);
        ps.setString(2, nombre);
        ps.setInt(3, cantidad);
        ps.setInt(4, 1); // Categoria por defecto, puedes usar una lista desplegable en el futuro
        ps.setDouble(5, 0.0); // Precio por defecto
        ps.executeUpdate();

        // Insertar en movimientos_inventario
        String sqlMov = "INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad) VALUES (?, 'entrada', ?)";
        java.sql.PreparedStatement psMov = con.prepareStatement(sqlMov);
        psMov.setInt(1, id);
        psMov.setInt(2, cantidad);
        psMov.executeUpdate();

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jtable1.getModel();
        modelo.addRow(new Object[]{id, nombre, cantidad});

        javax.swing.JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");

        txtid.setText("");
        txtnombre.setText("");
        txtcantidad.setText("");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID y Cantidad deben ser números enteros.");
    } catch (java.sql.SQLIntegrityConstraintViolationException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un producto con ese ID.");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al agregar producto: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        txtcantidad = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 670, -1));

        btnagregar.setBackground(new java.awt.Color(0, 255, 0));
        btnagregar.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btneditar.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        btneditar.setText("Editar ");
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        btneliminar.setBackground(new java.awt.Color(255, 0, 0));
        btneliminar.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 51, 51));
        btneliminar.setText("Eliminar");
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel2.setText("Nombre del producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtnombre.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 210, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel3.setText("Id del producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtid.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, -1));

        label1.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        label1.setText("Cantidad");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        txtcantidad.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 70, -1));

        btnsalir.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        btnsalir.setText("Salir");
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
    btnagregar.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        agregarProducto();
    }
});


    }//GEN-LAST:event_btnagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable1;
    private java.awt.Label label1;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
