
package punto;


/**
 *
 * @author chiqu
 */
public class panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventas = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        empleados = new javax.swing.JButton();
        cortecaja = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        ReporteVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel");
        setMinimumSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ventas.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        ventas.setText("ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });
        getContentPane().add(ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 200, -1));

        inventario.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        inventario.setText("inventario");
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, -1));

        empleados.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        empleados.setText("empleados");
        empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosActionPerformed(evt);
            }
        });
        getContentPane().add(empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, -1));

        cortecaja.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        cortecaja.setText("corte de caja");
        cortecaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortecajaActionPerformed(evt);
            }
        });
        getContentPane().add(cortecaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 230, -1));

        salir.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 160, -1));

        ReporteVenta.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        ReporteVenta.setText("Reporte de ventas");
        ReporteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteVentaActionPerformed(evt);
            }
        });
        getContentPane().add(ReporteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
     System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
    inventarioentario inv = new inventario();
    inv.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_inventarioActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
    jfventas ventas = new jfventas();
    ventas.setVisible(true);
    this.dispose();
     System.out.println("Botón ventas presionado");


    }//GEN-LAST:event_ventasActionPerformed

    private void ReporteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteVentaActionPerformed

    }//GEN-LAST:event_ReporteVentaActionPerformed

    private void empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosActionPerformed
        empleados emp = new empleados();
        emp.setVisible(true);
        this.dispose(); // Opcional: cierra la ventana actua
    }//GEN-LAST:event_empleadosActionPerformed

    private void cortecajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortecajaActionPerformed
    cortedecaja corte = new cortedecaja();
    corte.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_cortecajaActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run () {
            new panel().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReporteVenta;
    private javax.swing.JButton cortecaja;
    private javax.swing.JButton empleados;
    private javax.swing.JButton inventario;
    private javax.swing.JButton salir;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
